csctapi: Fix format string warning printed when building for sh4.
The problem is that there are missing format string placeholders
for which the compiler rightfully complains with:
  icc_async.c: In function 'ICC_Async_Device_Init':
  icc_async.c:166: warning: too many arguments for format